#!/usr/bin/env bash
# Print POSIX shell assignments for a fresh VPS .env secret block.
# Redirect to a mode-600 file. Does not write secrets into git or logs.
set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required" >&2
  exit 1
fi

hex24() {
  openssl rand -hex 24
}

admin="$(hex24)"
migrator="$(hex24)"
runtime="$(hex24)"

cat <<EOF
# Generated by ops/gen-secrets.sh. POSIX shell assignments. chmod 600.
POSTGRES_ADMIN_USER=forests_admin
POSTGRES_ADMIN_PASSWORD=$admin
POSTGRES_DB=forests_wallet
POSTGRES_MIGRATOR_USER=forests_wallet_migrator
POSTGRES_MIGRATOR_PASSWORD=$migrator
POSTGRES_RUNTIME_USER=forests_wallet_runtime
POSTGRES_RUNTIME_PASSWORD=$runtime
DATABASE_URL=postgres://forests_wallet_runtime:${runtime}@postgres:5432/forests_wallet
MIGRATE_DATABASE_URL=postgres://forests_wallet_migrator:${migrator}@postgres:5432/forests_wallet
EOF
